export const ADD_PLACE = 'ADD_PLACE';
export const ADD_INCOME = 'ADD_INCOME';
export const ADD_INCOMEARRAY = 'ADD_INCOMEARRAY'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const ADD_EXPENSEARRAY = 'ADD_EXPENSEARRAY'
export const ADD_DATE = 'ADD_DATE'
export const ADD_DATE1 = 'ADD_DATE1'
export const ADD_INCOME_CATEGORY = 'ADD_INCOME_CATEGORY'
export const ADD_EXPENSE_CATEGORY = 'ADD_EXPENSE_CATEGORY'

// ADD_INCOMEARRAY